# Generated by Django 4.1.6 on 2023-03-22 19:17

from django.db import migrations, models
import resource.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('model_3d', models.FileField(blank=True, null=True, upload_to=resource.models.resource_files_path)),
                ('text', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'resource',
            },
        ),
    ]
