# Generated by Django 4.1.6 on 2023-02-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='module',
            table='modules',
        ),
    ]
