# Generated by Django 4.1.6 on 2023-02-10 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_answer_leveltest_typetest_user_answer_test_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.test'),
        ),
    ]
