# Generated by Django 4.1.6 on 2023-03-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='test',
        ),
    ]
