# Generated by Django 4.1.6 on 2023-03-22 19:17

from django.db import migrations, models
import django.db.models.deletion
import tests.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('types_test', '0001_initial'),
        ('levels_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=tests.models.test_image_path)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels_test.leveltest')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='types_test.typetest')),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
