# Generated by Django 4.1.6 on 2023-03-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
