# Generated by Django 4.1.6 on 2023-03-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_suggestions_attended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestions',
            name='content',
            field=models.TextField(error_messages={'blank': 'El contenido de la sugerencia no puede estar en blanco'}),
        ),
    ]
