# Generated by Django 4.1.6 on 2023-03-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0003_alter_suggestions_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='content',
            field=models.TextField(),
        ),
    ]
