# Generated by Django 4.1.6 on 2023-02-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_module_created_date_module_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningstyle',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='learningstyle',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
