# Generated by Django 4.1.6 on 2023-02-09 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
    ]
