# Generated by Django 4.1.6 on 2023-02-10 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_section_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='previous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='previous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.lesson'),
        ),
        migrations.AlterField(
            model_name='section',
            name='previous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.section'),
        ),
    ]
