# Generated by Django 4.1.6 on 2023-02-25 08:19

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_course_previous_alter_lesson_previous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.course_image_path),
        ),
    ]
