# Generated by Django 4.1.6 on 2023-03-14 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_course_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningstyle',
            name='name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'El correo ya esta registrado'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='learning_style',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='core.learningstyle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.role'),
        ),
    ]
