# Generated by Django 4.1.6 on 2023-03-15 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_learningstyle_name_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(error_messages={'blank': 'El nombre no puede estar en blanco'}, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='learning_style',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.learningstyle'),
        ),
    ]
