# Generated by Django 4.1.6 on 2023-03-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_user_email_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'El correo ya esta registrado'}, max_length=255, unique=True),
        ),
    ]
