# Generated by Django 4.1.6 on 2023-03-18 19:48

import core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('obj', models.FileField(blank=True, null=True, upload_to=core.models.resource_obj_path)),
                ('mtl', models.FileField(blank=True, null=True, upload_to=core.models.resource_mtl_path)),
            ],
            options={
                'db_table': 'resource',
            },
        ),
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('texture', models.FileField(blank=True, null=True, upload_to=core.models.textures_file_path)),
            ],
            options={
                'db_table': 'texture',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.lessons_image_path),
        ),
        migrations.AddField(
            model_name='lesson',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.resource'),
        ),
    ]
