# Generated by Django 4.1.6 on 2023-03-16 06:20

import core.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.lessons_image_path),
        ),
        migrations.AddField(
            model_name='lesson',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='resource',
            field=models.FileField(blank=True, null=True, upload_to=core.models.lessons_resource_path),
        ),
    ]
