# Generated by Django 4.1.6 on 2023-03-19 13:23

import core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('model_3d', models.FileField(blank=True, null=True, upload_to=core.models.resource_files_path)),
                ('text', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'resource',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.lessons_image_path),
        ),
        migrations.AddField(
            model_name='lesson',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.test_image_path),
        ),
        migrations.AlterField(
            model_name='course',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.resource'),
        ),
    ]
