# Generated by Django 4.1.6 on 2023-03-19 01:11

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_resource_texture_lesson_image_lesson_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.test_image_path),
        ),
        migrations.AlterField(
            model_name='course',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.course'),
        ),
    ]
