# Generated by Django 4.1.6 on 2023-03-19 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_resource_lesson_image_lesson_reference_test_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
