# Generated by Django 4.1.6 on 2023-03-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_test_image_alter_course_previous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
