# Generated by Django 4.1.6 on 2023-03-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_lesson_previous_alter_section_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_answer',
            name='date_answer',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
